from setuptools import setup

setup(
    name='sls_api',
    packages=['sls_api'],
    version="1.2.0",
    include_package_data=True,
    install_requires=[
        'argon2_cffi==21.*',
        'beautifulsoup4==4.*',
        'flask==1.*',
        'flask-jwt-extended==3.*',
        'flask-sqlalchemy==2.*',
        'flask-cors==3.*',
        'flasgger==0.9.*',
        'lxml==4.*',
        'mysqlclient==2.*',
        'passlib==1.*',
        'psycopg2-binary==2.*',
        'raven[flask]==6.*',
        'ruamel.yaml==0.17.*',
        'requests==2.*',
        'simplejson==3.*',
        'sqlalchemy==1.*',
        'Pillow==8.*,>=8.3.2',
        'werkzeug==1.*',
        'elasticsearch==7.*'
    ]
)
